{
 "title": "Linux",
 "tags": [
  "o11y",
  "linux"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(node_exporter_build_info,instance)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\",instance=\"$instance\"}[$__rate_interval])) by (mode) / on (instance) group_left count(node_cpu_seconds_total{mode=\"idle\",instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Saturation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\",instance=\"$instance\"}[$__rate_interval])) by (cpu)",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Pressure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_pressure_cpu_waiting_seconds_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Waiting"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\"}",
     "legendFormat": "total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\"} - node_memory_MemFree_bytes{instance=\"$instance\"} - node_memory_Buffers_bytes{instance=\"$instance\"} - node_memory_Cached_bytes{instance=\"$instance\"}",
     "legendFormat": "used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$instance\"}",
     "legendFormat": "cached"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"$instance\"}",
     "legendFormat": "buffers"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_SwapFree_bytes{instance=\"$instance\"}",
     "legendFormat": "used"
    },
    {
     "expr": "node_memory_SwapCached_bytes{instance=\"$instance\"}",
     "legendFormat": "cached"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"$instance\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Memory pressure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_pressure_memory_stalled_seconds_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "stalled"
    },
    {
     "expr": "rate(node_pressure_memory_waiting_seconds_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "waiting"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_written_bytes_total{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(rate(node_disk_read_bytes_total{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "Disk IO duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_disk_write_time_seconds_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "write {{ device }}"
    },
    {
     "expr": "rate(node_disk_read_time_seconds_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "read {{device}}"
    }
   ]
  },
  {
   "title": "Disk pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_pressure_io_stalled_seconds_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "stalled"
    },
    {
     "expr": "rate(node_pressure_io_waiting_seconds_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "waiting"
    }
   ]
  },
  {
   "title": "Disk space",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by (fstype, mountpoint) (node_filesystem_size_bytes{instance=\"$instance\"})",
     "legendFormat": "size"
    },
    {
     "expr": "max by (mountpoint) (node_filesystem_avail_bytes{instance=\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "100 - (100 * max by (mountpoint) (node_filesystem_avail_bytes{instance=\"$instance\"} / node_filesystem_size_bytes{instance=\"$instance\"}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "100 - (100 * max by (mountpoint) (min_over_time(node_filesystem_avail_bytes{instance=\"$instance\"}[$__range]) / max_over_time(node_filesystem_size_bytes{instance=\"$instance\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}