---
- name: Preflight
  ansible.builtin.include_tasks: preflight.yml
  tags:
    - authp_install
    - authp_configure
    - authp_run

- name: Install
  ansible.builtin.include_tasks:
    file: install.yml
    apply:
      become: true
  tags:
    - authp_install

- name: Configure
  ansible.builtin.include_tasks:
    file: configure.yml
    apply:
      become: true
  tags:
    - authp_configure

- name: Ensure Authp is enabled on boot
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: authp
    enabled: true
    state: started
  when:
    - not ansible_check_mode
  tags:
    - authp_run
